the-qa-company/qEndpoint

hdt-qs-frontend/package-lock.json, hdt-qs-frontend/package.json, hdt-qs-frontend/src/App.tsx, hdt-qs-frontend/src/common/api.ts, hdt-qs-frontend/src/common/config/config.json, hdt-qs-frontend/src/common/http.ts, hdt-qs-frontend/src/common/local-storage.ts, hdt-qs-frontend/src/common/react-utils.ts, hdt-qs-frontend/src/components/Control/IsUp.module.scss, hdt-qs-frontend/src/components/Control/IsUp.tsx, hdt-qs-frontend/src/components/Control/index.module.scss, hdt-qs-frontend/src/components/Control/index.tsx, hdt-qs-frontend/src/components/NavigationBar/index.tsx, hdt-qs-frontend/src/components/SparqlEndpoint/index.tsx, hdt-qs-frontend/src/components/Upload/Dnd.module.scss, hdt-qs-frontend/src/components/Upload/Dnd.tsx, hdt-qs-frontend/src/components/Upload/index.module.scss, hdt-qs-frontend/src/components/Upload/index.tsx, hdt-qs-frontend/src/index.tsx
Issue resolved: #13 
New UI!
---
=> New UI - Control Panel, Upload, Endpoint

.gitignore, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/Application.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSail.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSailOptions.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SailCompilerSchema.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/controller/EndpointController.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/controller/Sparql.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/controller/WebConfig.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/FileUtils.java, hdt-qs-backend/src/main/resources/application-prod.properties, hdt-qs-backend/src/main/resources/application.properties, hdt-qs-backend/src/main/resources/repo_model.ttl, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/compiler/DebugOptionTestUtils.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/controller/FileUploadTest.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/controller/TripleSourceTest.java, hdt-qs-backend/src/test/resources/application.properties
Issue resolved (if any): #38 
It adds config to the repo_model file
---
=> GH-38 config files

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/HDTConverter.java
Issue resolved (if any): #76
Fix datatype issue
---
=> GH-76 fix datatypes

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/controller/Sparql.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreConnection.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreTripleIterator.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointTripleSource.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/exception/EndpointStoreException.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/exception/EndpointTimeoutException.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/store/EndpointStoreConnectionTest.java
Issue resolved (if any): #80
Add a new Exception for EndpointStorage connection to allow a timeout after a delay with tests
---
=> GH-80 fix timeout

hdt-qs-backend/pom.xml, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreConnection.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/rdf/ClosableResult.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/store/EndpointSPARQL11QueryComplianceTest.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/store/EndpointSPARQL11UpdateComplianceTest.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/store/QueryTest.java, hdt-qs-backend/src/test/resources/issues/issue_94/dataset.nt, hdt-qs-backend/src/test/resources/issues/issue_94/query1.sparql, hdt-qs-backend/src/test/resources/issues/issue_94/query2.sparql
Issue resolved (if any): #94 
I've updated RDF4J, resolved tests issues with non-closed operations and added a test to check #94.
---
=> GH-94 update rdf4j and fix non-closed operations

hdt-qs-backend/pom.xml
Reverts the-qa-company/qEndpoint#10
=> Revert "Bump junit from 4.13 to 4.13.2 in /hdt-qs-backend"

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java
Issue resolved (if any): #119
fix non closed connection
---
=> Gh-119 fix non closed connection

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreConnection.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreUtils.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/sail/FilteringSailConnection.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/sail/MultiInputFilteringSailConnection.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/sail/filter/LanguageSailFilter.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/sail/filter/LuceneMatchExprSailFilter.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/sail/filter/OpSailFilter.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/sail/filter/PredicateSailFilter.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/sail/filter/SailFilter.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/sail/filter/TypeSailFilter.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/utils/sail/SailTest.java
Issue resolved (if any): #122 
Fix filter sub connections and add tests
---
=> GH-122 Fix filter sub connections and add tests

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/model/HDTValue.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/model/SimpleBNodeHDT.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/model/SimpleIRIHDT.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/model/SimpleLiteralHDT.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreConnection.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/HDTConverter.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/MergeRunnable.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/MergeRunnableStopPoint.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/store/EndpointStoreNotifyTest.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/utils/sail/SailTest.java
Issue resolved (if any): #127 
I've added a check if the store is merging before notifying the add/remove
---
=> GH-127 fix notifying 

hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/store/EndpointStoreNotifyTest.java
Issue resolved (if any): #127
Improve #128 with better tests
---
=> GH-127 Add better tests

hdt-qs-backend/pom.xml, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/Application.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/config/WebMvcConfig.java
Merge to verify the code before the release
=> Merge dev into master

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreConnection.java
Issue resolved (if any): #167 
Sync the writer for multi-threaded delete
---
=> GH-167 sync writer

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSail.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SailCompiler.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SailCompilerValidator.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/sail/LuceneSailCompiler.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/sail/helpers/LuceneSailBuilder.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/compiler/SailCompilerTest.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/store/EndpointStoreNotifyTest.java
Issue resolved (if any): #189 
Add verification tool to check if a model file is correct
---
=> GH-189 model verification

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SailCompilerSchema.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/sail/FilterLinkedSailCompiler.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/sail/filter/LuceneGeoExprSailFilter.java
Issue resolved (if any): #196 
Add the ``mdlc:typeFilterLuceneGeoExp`` type filter to allow to use GeoSPARQL queries in a node
---
=> GH-196 Add GEO Expr Filter

hdt-qs-backend/pom.xml, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSail.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSailOptions.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SailCompilerSchema.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/controller/Sparql.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/model/SimpleLiteralHDT.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointFiles.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/MergeRunnable.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/OverrideHDTOptions.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/client/RDF4JClientTest.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/controller/FileUploadTest.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/utils/sail/SailTest.java, pom.xml, scripts/set_version.sh
Issue resolved (if any): #198 
I've updated the RDFHDT version to 3.0.7.
It also use the new catTree generation and catDiff method.
---
=> GH-198 Update RDFHDT to 3.0.7

.github/workflows/be-test.yml, .github/workflows/pr-test-be.yml, .gitignore, hdt-qs-backend/pom.xml, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreUtils.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/MergeRunnable.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/OverrideHDTOptions.java, pom.xml
Issue resolved (if any): #221 
Updated HDT to 3.0.8
---
=> GH-221 Update RDFHDT

hdt-qs-backend/pom.xml, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/OverrideHDTOptions.java
Issue resolved (if any): #221 (again)
update RDFHDT to 3.0.9
---
=> GH-221 Update RDFHDT to 3.0.9

.github/workflows/package-build.yml, scripts/Dockerfile-wikidata-all, scripts/loadData.sh, scripts/loadDataAll.sh
Issue resolved (if any): #225 
I've added a new docker image for the Wikidata-all HDT we computed.
---
=> GH-225 add wikidata-all docker image

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreTripleIterator.java
Issue resolved (if any): # 
Add timeout in the endpoint store iterator to allow the timeout 
---
=> Add timeout

qendpoint-core/src/test/resources/logback.xml
Issue resolved (if any): #254 
Logger config in the wrong directory
---
=> GH-254 Fix logging

.gitignore, qendpoint-core/pom.xml, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/compact/sequence/SequenceLog64Big.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/unsafe/MemoryUtils.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/unsafe/UnsafeLongArray.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/disk/LargeLongArray.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/io/IOUtil.java, qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/compact/sequence/LargeArrayTest.java, qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/unsafe/MemoryUtilsTest.java, qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/unsafe/UnsafeLongArrayTest.java
Issue resolved (if any): #257 
Replace of the JLargeArray with an equivalent class.
---
=> GH-257 replace JLargeArray with memory array

.github/workflows/pr-test.yml, .github/workflows/test.yml, hdt-qs-backend/pom.xml, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/Application.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/controller/EndpointController.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/controller/LogController.java, pom.xml, qendpoint-core/pom.xml
Issue resolved (if any): #261 
Update springboot to 3.0.2 and update logback to 1.4.5
---
=> GH-261 Update springboot to 3.0.2, update Logback to 1.4.5

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/MergeRunnable.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/diskimport/MapOnCallHDT.java
Issue resolved (if any): #273 
Fix issue generated by #271 
---
=> GH-271 Fix issue with deadlock from #273

scripts/Dockerfile
Issue resolved (if any): #282 
Set Java version to 17
---
=> GH-282 Set Java Docker image to JDK-17

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/MergeRunnable.java
Issue resolved (if any): #276 
Delete the native stores in the merge phase to reduce disk usage
---
=> GH-276 delete stores

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/ConfigSailConnection.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreConnection.java, hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/rdf/QEPSPARQLResultsJSONWriter.java, hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/compiler/ConfigSailConnectionTest.java
Issue resolved (if any): #280 
Temp version with only the backend part
---
=> GH-280 query plan

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/rdf/QEPSPARQLResultsJSONWriter.java
Issue resolved (if any): #292
I check if the value is null
---
=> GH-292 fix npe

qendpoint-cli/bin/qepSearch.sh
Issue resolved (if any): #308
Replace bad class name to new one
---
=> GH-308 fix qepSearch.sh

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/enums/RDFNotation.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/exceptions/ParserException.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/quads/QuadString.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/rdf/RDFParserFactory.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/rdf/parsers/JenaNodeFormatter.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/rdf/parsers/RDFParserRIOT.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/rdf/parsers/RDFParserSimple.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/triples/TripleString.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/LargeFakeDataSetStreamSupplier.java, qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/rdf/parsers/RDFParserSimpleTest.java
Issue resolved (if any): #358
Add NQ Simple parser
---
=> GH-358 add simple NQ parser with QuadString version of TripleString

qendpoint-store/pom.xml, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java
Issue resolved (if any): #379 
Update RDF4j
---
=> GH-379 Update RDF4J to 4.3.2

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/DictionaryPrivate.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/BaseDictionary.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/DictionaryPFCOptimizedExtractor.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/MultDictionaryPFCOptimizedExtractor.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/MultipleBaseDictionary.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/MultipleLangBaseDictionary.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/MultipleSectionDictionaryLangPFCOptimizedExtractor.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/enums/TripleComponentRole.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/HDTImpl.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/iterator/DictionaryTranslateIteratorBuffer.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/model/SimpleIRIHDT.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointFiles.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreTripleIterator.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/HDTConverter.java, qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/EndpointNodeMSDLTest.java, qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/EndpointStoreTest.java
Issue resolved (if any): #378
Fix mapped HDT optimizers and add converter node type usage
---
=> GH-378 MSDL fixup

qendpoint-frontend/src/components/SparqlEndpoint/plugins/queryPlan.ts, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java
Issue resolved (if any): #387
Add check and remove query plan
---
=> GH-387 fts explain error

qendpoint-backend/src/main/java/com/the_qa_company/qendpoint/controller/EndpointController.java, qendpoint-backend/src/main/java/com/the_qa_company/qendpoint/controller/Sparql.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSailOptions.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/SailCompiler.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/SailCompilerSchema.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/MergeRunnable.java, qendpoint-store/src/main/resources/repo_model.ttl
Issue resolved (if any): #395 
Add `mdlc:dumpLocation` to the repo model.
Allow to use mdlc:parsedString default options in option config.
Add `is_dumping` to the api.
---
=> GH-395 dump getter, config with a little fix

scripts/Dockerfile-wikidata, scripts/loadData.sh, scripts/wikidata-prefixes.sparql
Issue resolved (if any): #404 
Adds WD prefixes to the docker image
---
=> GH-404 Add Wikidata prefixes in WD image

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/MultipleLangBaseDictionary.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/utils/RDFStreamUtils.java, qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/EndpointNodeMSDLTest.java
Issue resolved (if any): #409
Fixing return values for the string resolving in the MSDL implementation
---
=> GH-409 Fix MSDL return values for string resolving

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/MultipleLangBaseDictionary.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/model/SimpleIRIHDT.java, qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/EndpointNodeMSDLTest.java
Issue resolved (if any): #409 (again)
Return -1 for bad predicate results
---
=> GH-409 fix predicate return for MSDL

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/MultipleLangBaseDictionary.java
Issue resolved (if any): #416 
Fix the MSDL if a section is empty
---
=> GH-416 Fix MSDL search

qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreDump.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/MergeRunnable.java
Issue resolved (if any): #415 
Dump the FOQ index with the store in the dump method
---
=> GH-415 Add FOQ dump

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/HDTManagerImpl.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/rdf/RDFParserCallback.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/rdf/RDFParserFactory.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/rdf/parsers/RDFParserDir.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/LargeFakeDataSetStreamSupplier.java, qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/hdt/HDTManagerTest.java
Issue resolved (if any): #422
Create the loader before the call to the input file so it can check for directories
---
=> GH-422 fix dir loader

qendpoint-cli/bin/hdtDiffCat.bat, qendpoint-cli/bin/hdtDiffCat.ps1, qendpoint-cli/bin/hdtDiffCat.sh, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/tools/HDTDiffCat.java
Issue resolved (if any): #435 
---
=> GH-435 add diffcat tool

qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSail.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/SailCompilerConfig.java
Issue resolved (if any): #448
Add method to config the compiler in the CompiledSail builder
---
=> GH-448 add compiler config in the CompiledSail builder

qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/ComplianceTest.java, qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/Utility.java, qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/experimental/ExperimentalQEndpointSPARQL11ComplianceQueryTest.java, qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/experimental/ExperimentalQEndpointSPARQL11ComplianceUpdateTest.java
Issue resolved (if any): # 
---
=> Fix compliance tests

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/WriteMultipleSectionDictionaryLang.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/LiteralsUtils.java
Issue resolved (if any): #474 
Fix the literal parsing
---
=> GH-474 fix literal parsing

qendpoint-backend/src/main/java/com/the_qa_company/qendpoint/controller/EndpointController.java, qendpoint-backend/src/main/java/com/the_qa_company/qendpoint/controller/Sparql.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/kcat/KCatImpl.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/HDTManager.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/HDTManagerImpl.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/HDTResult.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/diskimport/AsyncCatTreeWorker.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/diskimport/CatTreeImpl.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/diskimport/MapOnCallHDT.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/options/HDTOptionsKeys.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/QEPCore.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/QEPDataset.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/QEPDatasetContext.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/QEPMap.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/QEPMapSyncIOException.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/iterator/CatQueryCloseable.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/iterator/CloseableAttachQueryIterator.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/iterator/QueryCloseableIterator.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/search/QEPComponentTriple.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/search/QEPComponentTripleFreeze.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/search/QEPComponentTripleSimple.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/storage/search/QEPDatasetIterator.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/io/IOUtil.java, qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/hdt/HDTManagerTest.java, qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/storage/QEPCoreTest.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSail.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java, qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreTripleIterator.java, qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/hand/HandTest.java
Issue resolved (if any): #477
Reimplement #470
=> GH-477 merge 470

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/MultipleSectionDictionaryLangPFCOptimizedExtractor.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/HDTManagerImpl.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/options/HDTOptionsKeys.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/StringUtil.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/io/IOUtil.java
Issue resolved (if any): #480 
Add options to pre download a URL:
- `loader.predownloadURL` : Enable the pre download
- `loader.predownloadURL.file` : Give the temp file path, by default a temporary file is created
- `loader.predownloadURL.noDelete` : Do not delete the temp file after generation
- `loader.predownloadURL.retry` : Amount of retry after a fail
---
=> GH-480 pre download dataset

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/diskimport/AsyncCatTreeWorker.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/diskimport/CatTreeImpl.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/iterator/utils/FluxStopTripleStringIterator.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/iterator/utils/FluxStopTripleStringIteratorImpl.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/options/HDTOptionsKeys.java
Issue resolved (if any): #498 
Add bounds to errors in the generation context
---
=> GH-498 find bounds errors

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/HDTManagerImpl.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/options/HDTOptionsFile.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/io/IOUtil.java, qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/util/io/IOUtilTest.java
Issue resolved (if any): #499 
Reload the download at the same location if we know the size
---
=> GH-499 Reload dl

qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSail.java
=> GH-537 add name other cmd

qendpoint-frontend/package-lock.json, qendpoint-frontend/package.json
Issue resolved (if any): #567
Update formatter
---
=> GH-567 format

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/compact/bitmap/Bitmap375Big.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/disk/AbstractLongArray.java, qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/disk/LongArray.java, qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/util/disk/AbstractLongArrayTest.java
Issue resolved (if any): #573 
---
=> GH-573 fix calc with more tests and fix for index+1 issue

qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreDump.java
Issue resolved (if any): #583 
Add check before path copies
---
=> GH-583 Fix dump copy call

scripts/Dockerfile
Issue resolved (if any): #602
Updated the base image
Startup is now working..
> 2025-03-20 22:04:40 21:04:40.706 [main] INFO  o.s.s.c.a.a.c.InitializeUserDetailsBeanManagerConfigurer$InitializeUserDetailsManagerConfigurer - Global AuthenticationManager configured with UserDetailsService bean with name inMemoryUserDetailsManager
> 2025-03-20 22:04:40 21:04:40.757 [main] INFO  o.s.b.a.w.s.WelcomePageHandlerMapping - Adding welcome page: class path resource [static/index.html]
> 2025-03-20 22:04:40 21:04:40.929 [main] INFO  o.s.b.a.e.web.EndpointLinksResolver - Exposing 14 endpoints beneath base path '/actuator'
> 2025-03-20 22:04:41 21:04:41.101 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port 1234 (http) with context path '/'
> …
=> GH-602 update Dockerfile

qendpoint-backend/pom.xml, qendpoint-core/pom.xml, qendpoint-store/pom.xml, qendpoint-store/src/test/java/com/the_qa_company/qendpoint/deps/BeanUtilsOpenCsvTest.java
Issue resolved (if any): #607 
Update, force beanutils to 1.11.0, but a test was added
---
=> GH-607 Update Spring to 3.4.5 and commons-beanutils to 1.11.0
