hdt-qs-backend/pom.xml

Reverts the-qa-company/qEndpoint#4, the tests weren't passing, but without triggering an error

Revert "Bump junit from 4.13 to 4.13.2 in /hdt-qs-backend"

---

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSail.java
hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java
hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/controller/EndpointController.java
hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/controller/Sparql.java
hdt-qs-frontend/src/components/Control/index.tsx

Issue resolved (if any): #34
Disable the reindex button by adding the `/has_index` method in the API and linking it to the front-end
---

GH-34 disable reindex button if no Lucene sail is connected to the endpoint

---

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/utils/FormatUtils.java
hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/utils/FormatUtilsTest.java

Issue resolved (if any): #108 
Allow to use q= in the accept header
---

GH-108 Fix FormatUtils' header methods

---

hdt-qs-backend/src/main/resources/repo_model.ttl

Issue resolved (if any): #228 
It comment the full text lucene node in the default repo_model.ttl file
---

GH-228 Remove the Full Text in the default model

---

hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointFiles.java
qendpoint-cli/bin/hdtconvert.bat
qendpoint-cli/bin/hdtconvert.ps1
qendpoint-cli/bin/hdtconvert.sh
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/MultipleSectionDictionary.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/UnmodifiableDictionarySectionPrivate.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/section/WriteDictionarySection.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/enums/TripleComponentOrder.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/Converter.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/HDT.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/HDTManagerImpl.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/HDTImpl.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/converter/FSDToMSDConverter.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/converter/MSDToFSDConverter.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/converter/ObjectReSortIterator.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/iterator/utils/EmptyIterator.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/iterator/utils/MergeExceptionIterator.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/options/HDTOptions.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/options/HDTOptionsKeys.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/tools/HDTConvertTool.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/triples/impl/WriteBitmapTriples.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/io/CloseOnceInputStream.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/io/CloseOnceOutputStream.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/string/ByteString.java
qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/dictionary/impl/section/WriteDictionarySectionTest.java
qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/hdt/impl/converter/ConverterTest.java
qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/util/LargeFakeDataSetStreamSupplier.java

Issue resolved (if any): #270
Add converter to convert HDT dictionary, it also add a hdtConvert script, usage:
```powershell
hdtConvert.ps1 <input hdt> <output hdt> <output dictionary type>
```
---

GH-270 Add converter to convert HDT dictionaries

---

.github/workflows/pr-test.yml
.github/workflows/test.yml
hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSail.java
hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/ConfigSailConnection.java
hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java
hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java
hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreConnection.java
hdt-qs-backend/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreQueryPreparer.java
hdt-qs-backend/src/test/java/com/the_qa_company/qendpoint/compiler/ConfigSailConnectionTest.java

Issue resolved (if any): #279
It add an option tool for the endpoint connection,
you need to add `#config` or `#config:value` lines before the query you want to run
example with the `no_optimizer` config
```rq
#no_optimizer
SELECT * {
?s ?p ?o .
<http://a> <http://p> ""
}
```
I've also added an option to add a value, maybe for later
```rq
#config_key:config value
SELECT * {
?s ?p ?o .
}
```
---

GH-279 optimizer disabler and query config

---

.github/workflows/package-build.yml
scripts/hashfiles.sh

Issue resolved (if any): #303 
It will add the sha512 in the release notes
---

GH-303 add file hashes in the release note

---

qendpoint-backend/src/main/java/com/the_qa_company/qendpoint/controller/EndpointController.java
qendpoint-backend/src/main/java/com/the_qa_company/qendpoint/controller/Sparql.java
qendpoint-frontend/package-lock.json
qendpoint-frontend/package.json
qendpoint-frontend/src/components/SparqlEndpoint/index.tsx
qendpoint-frontend/src/components/SparqlEndpoint/plugins/queryPlan.ts
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java

Issue resolved (if any): #280
I've added the query plan, it looks like this:
I've also added the `QueryConfig` header to the Sparql mapping to define config without having to specify it in the query
---

GH-280 add query plan in frontend

---

.gitignore
qendpoint-backend/src/main/java/com/the_qa_company/qendpoint/controller/EndpointController.java
qendpoint-backend/src/main/java/com/the_qa_company/qendpoint/controller/Sparql.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/options/ControlInformation.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSail.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSailEndpointStoreDump.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreConnection.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreDump.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/MergeRunnable.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/utils/FileUtils.java

Issue resolved (if any): #391 
A not optimized system to dump the dataset from a running endpointstore, it uses 2 particular states of the endpoint during the merge
---

GH-391 Dump dataset while running the endpoint

---

qendpoint-backend/src/main/java/com/the_qa_company/qendpoint/controller/EndpointController.java
qendpoint-backend/src/main/java/com/the_qa_company/qendpoint/controller/Sparql.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/federation/SPARQLServiceWikibaseLabelResolver.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/federation/WikibaseLabelService.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreQueryPreparer.java

Issue resolved (if any): #399 
Handle `AcceptLanguage` header in controller.
Add `acceptLanguageHeader` parameter to some of `Sparql::execute` methods.
Use an `AbstractQueryModelVisitor` to find the `"[AUTO_LANGUAGE]"` literal and replace it according to the accept header.
---

GH-399 support [AUTO_LANGUAGE]

---

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/impl/HDTImpl.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/header/PlainHeaderIterator.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/iterator/DictionaryTranslateIterator.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/iterator/DictionaryTranslateIteratorBuffer.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/options/HDTOptions.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/rdf/parsers/JenaModelIterator.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/triples/IteratorTripleID.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/triples/IteratorTripleString.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/triples/impl/BitmapTriplesIterator.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointFiles.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreConnection.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreTripleIterator.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/MergeRunnable.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/tools/QEPSearch.java
qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/EndpointMultIndexSPARQL11QueryComplianceTest.java
qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/EndpointMultIndexSPARQL11UpdateComplianceTest.java
qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/MergeRestartTest.java
qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/Utility.java

Issue resolved (if any): #440
Add delete bitmaps for the option `bitmaptriples.index.others`
---

GH-440 Add delete bitmap to multiple co-indexes

---

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/Dictionary.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/MultipleBaseDictionary.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/dictionary/impl/MultipleLangBaseDictionary.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/tools/HDTVerify.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/SparqlRepository.java

Issue resolved (if any): #451 
Add support for MSDL/Graph dict in hdtVerify CLI
---

GH-451 Add support for MSDL/GRAPH Dictionary in HDT verify

---

qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreConnection.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreTripleIterator.java

Issue resolved (if any): #455 
Add the option `qendpoint.delete.disable` to disable the deletes in the qendpoint.
---

GH-455 Disable delete bitmap feature

---

qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStoreTripleIterator.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/utils/BitArrayDisk.java

Issue resolved (if any): #455 
Remove the need to add the option added in #446 when it is not required.
---

GH-455 Disable delete bitmap when not required

---

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/exceptions/SignatureIOException.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/triples/impl/BitmapTriples.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/triples/impl/BitmapTriplesIndexFile.java
qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/triples/impl/BitmapTriplesIndexFileTest.java

Issue resolved (if any): #458 
Regenerate the other indexes if the signature is wrong
---

GH-458 Regenerate index if signature is wrong

---

qendpoint-cli/bin/qepSearch.ps1
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/tools/QEPSearch.java

Issue resolved (if any): #460 
Add -csv option to qepsearch to dump profiler into csv files.
It'll group the section with the same element names and depth. Example for a rdf2hdt cat generation:
```
depth-0/prof-0.csv
depth-1/prof-0.csv
depth-1/prof-1.csv
depth-2/prof-0.csv
depth-2/prof-1.csv
```
Usage:
```pwsh
qepSearch [input] -csv [output_dir]
```
---

GH-460 prof to csv

---

qendpoint-store/src/main/java/com/the_qa_company/qendpoint/functions/Log.java
qendpoint-store/src/main/java/com/the_qa_company/qendpoint/store/EndpointStore.java
qendpoint-store/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.algebra.evaluation.function.Function
qendpoint-store/src/test/java/com/the_qa_company/qendpoint/functions/LogTest.java

Issue resolved (if any): #464 
Add the log function inside the SPARQL endpoint. It can be used with `<http://the-qa-company.com/qendpoint/#log>(value, base = 10)`. For example:
```sparql
PREFIX qep: <http://the-qa-company.com/qendpoint/#>
SELECT * {
VALUES ?number { 10 80 420 10000 20000 1000000 }
BIND (qep:log(?number) AS ?logNumberDef)
BIND (qep:log(?number, 10) AS ?logNumber10)
BIND (qep:log(?number, 16) AS ?logNumber16)
BIND (qep:log(?number, 2) AS ?logNumber2)
}
```
---

GH-464 Add log function to SPARQL

---

qendpoint-cli/bin/indexhdtrepo.bat
qendpoint-cli/bin/indexhdtrepo.ps1
qendpoint-cli/bin/indexhdtrepo.sh
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/exceptions/SameChecksumException.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/hdt/HDTManagerImpl.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/options/HDTOptionsKeys.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/tools/HDTAutoIndexer.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/StringUtil.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/crc/CRCInputStream.java
qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/util/StringUtilTest.java
qendpoint-store/src/test/java/com/the_qa_company/qendpoint/store/hand/HandTest.java

Issue resolved (if any): #482 
Add tool to loop a generation, same options as the rdf2hdt, in takes in param the path and then the path to download it, it has 3 options in the specs:
- `autoIndexer.sleepTimeMillis`: Time between each generation in millis (default 10s)
- `autoIndexer.indexName`: The name of the index without the ".hdt", (default "index_dev")
- `autoIndexer.runOnlyRemove`: Do not run in loop local files (default true)
**Example**
```pwsh
indexhdtrepo.ps1 https://data.wikibase.the-qa-company.com/dump_latest.ttl wikibase -config option.spec
```
---

GH-482 Auto indexer

---

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/options/HDTOptionsKeys.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/triples/impl/BitmapTriples.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/triples/impl/BitmapTriplesIndexFile.java

Issue resolved (if any): #486 
Add option `bitmaptriples.index.allowOldOthers` with a default false to read v0 indexes
---

GH-486 Add option to read v0 indexes

---

qendpoint-store/src/main/java/com/the_qa_company/qendpoint/compiler/CompiledSail.java

Issue resolved (if any): #537 
Add lucene index id log when reindexing
---

GH-537 Add lucene index id to logs when reindexing

---

qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/compact/bitmap/Bitmap375Big.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/disk/AbstractLongArray.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/disk/LongArray.java
qendpoint-core/src/main/java/com/the_qa_company/qendpoint/core/util/disk/SyncLongArray.java
qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/hdt/HDTManagerTest.java
qendpoint-core/src/test/java/com/the_qa_company/qendpoint/core/util/disk/AbstractLongArrayTest.java

Issue resolved (if any): #573 
@hmottestad I'm not really sure if it fixes the issue. I replaced everything to long, but the most important part is updateEstimatedLocationArrayBucketSize.
I think the estimatedLocationBucketSize value was too small for the highest value. I kept the nearest power of 2 alignment, but I don't see where it was used.
---

GH-573 fix calc

---

qendpoint-frontend/src/components/SparqlEndpoint/index.tsx

Issue resolved (if any): #605 
Fix formatting issue by removing the async part (it was there to use an online formatter, but it was a stupid idea)
---

GH-605 Fix SPARQL formatting issues
